# Generated by Django 4.2.13 on 2024-07-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('CY', 'Cyclone'), ('TS', 'Tsunami'), ('OT', 'Other')], max_length=2)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('magnitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('affected_population', models.IntegerField(blank=True, null=True)),
                ('damage_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
